name: "Laravel Pint Check"

on:
  pull_request:
    branches: [ "production", "development" ]

jobs:
  laravel-pint:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Run Pint
      run: vendor/bin/pint --test
